# Generated by Django 5.1.4 on 2026-10-04 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("plan_project", "Plan project"),
                            ("breakdown_task", "Breakdown task"),
                            ("summarize_task", "Summarize task"),
                            ("project_insights", "Project insights"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("validation_error", "Validation error"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=30,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=30)),
                ("model_name", models.CharField(blank=True, max_length=60)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_interactions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "ai_ai_interaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="ai_ai_inter_user_id_e87126_idx"
                    ),
                    models.Index(
                        fields=["feature", "status"], name="ai_ai_inter_feature_ac33b9_idx"
                    ),
                ],
            },
        ),
    ]
